### PR TITLE
solved import error in latest version duel to numpy float and int  alias deprecated

### PR DESCRIPTION
**Pull request by shivamjadhav2000**
this changes resolve issue #10 
signed-off-by :shivam jadhav <jadhavshivam0228@gmail.com>

### CODE REVIEW

**Comment by shivamjadhav2000** [comment]
i have solved the issue

**Review by brandoncruz3 — COMMENTED** [review]
Works for me as well

**Comment by shivamjadhav2000** [comment]
Shall we merge the code ?

**Review by joshivanhoe — APPROVED** [review]
Thanks for making the change. Can we please merge this?

**Comment by shivamjadhav2000** [comment]
Yes we can merge this

**Comment by nikilp** [comment]
can this be released as a new version of the package?

**Comment by AleksTk** [comment]
@nikilp  I fixed this issue in a separate commit https://github.com/AleksTk/table-logger/commit/73fe1bf96bcf958b6a8477bdcc77d379facee117 since this code had a duplication issue. New release v0.3.7 should work fine.

**Pull request closed without merging**
